export default {
    SET_LOADING : 'SET_RECRUITMENT_LOADING',
    UNSET_LOADING : 'UNSET_RECRUITMENT_LOADING',

    SET_RECRUITMENTS : 'SET_RECRUITMENTS',
    SET_RECRUITMENT : 'SET_RECRUITMENT',

    SET_APPLICANTS : 'SET_APPLICANTS',
    SET_APPLICANT : 'SET_APPLICANT',

    PUBLISH_RECRUITMENT : 'PUBLISH_RECRUITMENT',
    DELETE_RECRUITMENT : 'DELETE_RECRUITMENT',

    CREATE_ADDON_SUCCESS : 'CREATE_ADDON_SUCCESS',

    SET_ACTIVE_STATUS : 'SET_ACTIVE_STATUS',

    SET_FAVOURITE_USER: 'SET_FAVOURITE_USER',

    EVALUATE_WORKER_SUCCESS : 'EVALUATE_WORKER_SUCCESS',

    INIT_STATE : 'INIT_STATE',

    SET_ERRORS : 'SET_ERRORS'
};
