export default {
    SET_LOADING : 'SET_CHAT_LOADING',
    UNSET_LOADING : 'UNSET_CHAT_LOADING',

    SET_RECRUITMENTS : 'SET_CHAT_RECRUITMENTS',
    SET_RECRUITMENT : 'SET_CHAT_RECRUITMENT',

    SET_APPLICANTS : 'SET_APPLICANTS',

    SET_FAVOURITES : 'SET_FAVOURITES',

    SET_CHATTING: 'SET_CHATTING',

    SET_MESSAGES: 'SET_MESSAGES',
    ADD_MESSAGES: 'ADD_MESSAGES',

    SET_UNREAD_MESSAGES: 'SET_UNREAD_MESSAGES',
    ADD_UNREAD_MESSAGE: 'ADD_UNREAD_MESSAGE',
    ADD_UNREAD_MESSAGES: 'ADD_UNREAD_MESSAGES',

    SEND_SUCCESS: 'SEND_SUCCESS',

    RECEIVE_MESSAGE: 'RECEIVE_MESSAGE',

    SET_ERRORS: 'SET_ERRORS'
};
