export default {
    SET_LOADING : 'SET_NOTICE_LOADING',
    UNSET_LOADING : 'UNSET_NOTICE_LOADING',

    SET_NOTICES: 'SET_NOTICES',

    SET_READ_NEWS: 'SET_READ_NEWS',

    SET_UNREAD_NOTICES: 'SET_UNREAD_NOTICES',
    ADD_UNREAD_NOTICE: 'ADD_UNREAD_NOTICE',

    DELETE_NEWS_SUCCESS: 'DELETE_NEWS_SUCCESS',

    SET_ERRORS: 'SET_ERRORS'
};
