export default {
    SET_LOADING : 'SET_APPLICATION_LOADING',
    UNSET_LOADING : 'UNSET_APPLICATION_LOADING',

    SET_APPLICATIONS : 'SET_APPLICATIONS',
    ADD_APPLICATIONS : 'ADD_APPLICATIONS',

    SET_APPLICATION : 'SET_APPLICATION',

    EVALUATE_RECRUITMENT_SUCCESS: 'EVALUATE_RECRUITMENT_SUCCESS',

    SET_ERRORS : 'SET_ERRORS'
};
