export default {
    SET_LOADING: 'SET_AUTH_LOADING',
    UNSET_LOADING: 'UNSET_AUTH_LOADING',

    REGISTER_SUCCESS : 'REGISTER_SUCCESS',
    REGISTER_FAIL : 'REGISTER_FAIL',
    USER_LOADED : 'USER_LOADED',
    AUTH_ERROR : 'AUTH_ERROR',
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGIN_FAIL : 'LOGIN_FAIL',
    LOGOUT : 'LOGOUT',

    SET_ALERT : 'SET_ALERT',
    REMOVE_ALERT : 'REMOVE_ALERT',

    GET_PROFILE : 'GET_PROFILE',
    GET_PROFILES : 'GET_PROFILES',
    UPDATE_PROFILE : 'UPDATE_PROFILE',
    PROFILE_ERROR : 'PROFILE_ERROR',
    CLEAR_PROFILE : 'CLEAR_PROFILE',
    ACCOUNT_DELETED : 'ACCOUNT_DELETED',


};
