export default {
    SET_LOADING : 'SET_USER_LOADING',
    UNSET_LOADING : 'UNSET_USER_LOADING',

    SET_USER_PROFILE: 'SET_USER_PROFILE',
    SET_PRODUCER_PROFILE: 'SET_PRODUCER_PROFILE',
    SET_WORKER_PROFILE: 'SET_WORKER_PROFILE',

    UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',

    SET_RECRUITMENTS: 'SET_USER_RECRUITMENTS',

    SET_FARMERS: 'SET_FARMERS',
    SET_FARMS: 'SET_FARMS',

    SET_ERRORS: 'SET_ERRORS',
};
