export default {
    SET_LOADING : 'SET_MATTER_LOADING',
    UNSET_LOADING : 'UNSET_MATTER_LOADING',

    SET_MATTERS: 'SET_MATTERS',
    ADD_MATTERS: 'ADD_MATTERS',
    SET_MATTER: 'SET_MATTER',

    SET_RECENT_MATTERS: 'SET_RECENT_MATTERS',

    SET_FAVOURITE: 'SET_FAVOURITE_MATTER',

    SET_FAVOURITE_MATTERS: 'SET_FAVOURITE_MATTERS',
    ADD_FAVOURITE_MATTERS: 'ADD_FAVOURITE_MATTERS',

    REMOVE_FAVOURITE_MATTER: 'REMOVE_FAVOURITE_MATTER',

    SET_ERRORS: 'SET_ERRORS',
};
